language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
before_install:
  - curl https://dapp.tools/install | sh
  - /home/travis/.nix-profile/etc/profile.d/nix.sh
  - dapp --use solc:0.5.12 test
jobs:
  include:
  - stage: test
    script:
      - dapp testnet &
      - ./bin/deploy.sh
      - npm run test