language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
before_install:
  - curl https://dapp.tools/install | sh
  - . $HOME/.nix-profile/etc/profile.d/nix.sh -iA dapp solc
jobs:
  include:
  - stage: test
    script:
      - dapp testnet &
      - ./bin/deploy.sh
    # - npm run test