language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
    - curl https://dapp.tools/install | sh
    - nix-env -f $HOME/.dapp/dapptools -iA dapp solc
jobs:
  include:
  - stage: tests
    script:
    - dapp testnet &
    - ./bin/deploy.sh
    - npm run test