language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: tests
    script:
    - npm run test
  - stage: Publish
    if: "(NOT type IN (pull_request)) AND (branch = master)"
    script:
      - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      - npm run publish

